# docker compose -f compose.dev.yaml up
# Development setup - source mounted read-only, build cache in Docker volumes

services:
  redlib:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "redlib"
    ports:
      - 8080:8080
    volumes:
      # Mount source code as read-only - code changes trigger rebuild
      - ./src:/redlib/src:ro
      - ./templates:/redlib/templates:ro
      - ./static:/redlib/static:ro
      - ./Cargo.toml:/redlib/Cargo.toml:ro
      - ./Cargo.lock:/redlib/Cargo.lock:ro
      - ./build.rs:/redlib/build.rs:ro
      # Build artifacts stay in Docker volumes (not on your disk)
      - redlib-target:/redlib/target
      - redlib-cargo:/usr/local/cargo
    environment:
      - RUST_LOG=debug
    networks:
      - redlib
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s

volumes:
  redlib-target:
  redlib-cargo:

networks:
  redlib:
